apiVersion: v1
entries:
  monolith-website:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-20T14:54:41.72898+01:00"
    description: A Helm chart for Kubernetes
    digest: fd98f4af3f22dc2dd6d55f3e1e43255eef4eda4dea8ae66032f0cffc8eaade5f
    name: monolith-website
    type: application
    urls:
    - https://liveclass-helm-repo.s3.amazonaws.com/charts/monolith-website-0.1.0.tgz
    version: 0.1.0
generated: "2023-05-20T14:54:41.728156+01:00"
