name: Deploy to AWS EKS

on:
  workflow_run:
    workflows:
      - "Publish Helm Chart (Dynamic version)"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
      EKS_CLUSTER_NAME: nonprod-dev
      K8S_NAMESPACE: liveclass

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Helm Chart from S3
        run: aws s3 cp s3://darey-helm-repo/monolith-website-0.1.0.tgz monolith-website-0.1.0.tgz

      - name: Extract Helm Chart
        run: tar -zxvf monolith-website-0.1.0.tgz

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure Kubernetes credentials
        uses: aws/eks-set-context@v1
        with:
          eks-region: ${{ env.AWS_REGION }}
          eks-cluster-name: ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy Helm Chart
        run: helm upgrade --install monolith-website ./monolith-website --namespace ${{ env.K8S_NAMESPACE }} --atomic --wait --timeout 5m --history-max 5

      - name: Validate Deployment
        run: kubectl rollout status deployment/monolith-website --namespace monolith